http:
  port: 8080
scylla:
  region: local
  endpoint: http://localhost:8000
  accessKey: test
  secretKey: test
nats:
  servers: nats://localhost:4222
  auth:
    username: test
    password: test
  topic: test.topic
  ACCOUNT_PUBLIC_KEY: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
  NATS_AUTH_NKEY_SEED: SAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
keycloak:
  jwksUri: http://localhost:8080/.well-known/jwks.json
alternator:
  endpoint: http://scylla-node:8000
  region: eu-west-1
tables:
  events: profiles_events
  snapshots: profiles_snapshots
  idem: profiles_idem
  locks: profiles_username_locks
snapshots:
  every: 100
idempotency:
  ttlSec: 86400
